### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by zgq7799** [GillesJ/sentivent-economic-event-detection#1]
Hello! After reading your code, I still don't know how you do data pre-processing. In line 102 of datahandler.py, is the .txt file in f"{dirp}/*.txt" corresponds to  .ann file in the sentivent data? If this is the case, in the unify_dataset function, I didn't find any examples with a label of 1. Maybe my understanding has a problem. Could you tell me your specific data pre-processing process and the correspondence between related data and programs? Thank you!

**Comment by GillesJ** [comment]
> Could you tell me your specific data pre-processing process and the correspondence between related data and programs? Thank you!

I went back and noticed that the preprocessed data directory needed by "dirp" is indeed not bundled with the Github or OSF.io repository. It contained the tokenized and sentence split instances in one file for each main event type. I was passed this data by a colleague and can not seem to find it now nor do I have the original script.

However, the full experiment reproduction data is available in the `/static/experiment_data.json` file. I have provided loaders in the project. It contains everything you need to reproduce my experiments. Holdin (training) and holdout test indices and split, original data, labels and some corpus metadata.

Hope it helps!
